schema_version = "1.0.0"
id = "meshgen"
version = "0.7.1"
name = "meshgen"
tagline = "Generate meshes with AI, with MLX support for Apple Silicon"
maintainer = "Hugging Face"
type = "add-on"
website = "https://github.com/huggingface/meshgen"
tags = [
    "Mesh",
    "Modeling",
    "Node",
    "Object",
    "Add Mesh",
    "System",
    "Pipeline",
    "User Interface",
]
blender_version_min = "4.2.0"
license = [
    "MIT",
]
copyright = [
    "2024 Hugging Face",
]
wheels = [
]

[permissions]
network = "Download required models"
files = "Install required models"
